### ISSUE TITLE
C# Script support (.csx files)

### ISSUE THREAD

**Issue by SlowLogicBoy** [natanfudge/Auto-Using#10]
Add support for C# Script files (.csx).

Currently suggestions work for some references, however if I use them, using statements are added at the top, ignoring `#r` and `#load` statements.

Also references from `#r` and `#load` are not considered.

More on C# scripting can be found in [dotnet-script](https://github.com/filipw/dotnet-script) repository.

**Comment by natanfudge** [comment]
Hey, thanks for the bug report/suggestion.
I expect to have the `using` placement fixed in a week or so, perhaps sooner if I manage to complete another ongoing task without too many issues.
In regards to references from libraries (`#r` and `#load`), those are not supported yet, including in normal C# files that have the packageReferences declared in `.csproj ` files. 
This is the next milestone, and beta builds of it are available in the `README` (although the support is only for normal C# files right now. I'll try to support it for .CSX as well ). Release will take quite a while, the amount of time depending on many factors along the way.

**Comment by natanfudge** [comment]
The first part is fixed in [0.7.8](https://marketplace.visualstudio.com/items/Fudge.auto-using/changelog).
The second part is being tracked separately in #11 so I can mark the first part as done by closing this issue.
